language: php
php:
- 7.2
- 8.0
- 8.1
- 8.2
- 8.3
- hhvm
matrix:
  include:
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 8.0
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 8.1
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 8.2
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 8.3
      env: COMPOSER_FLAGS="--prefer-lowest"
before_script:
  - composer validate
  - composer self-update
  - composer update --no-interaction ${COMPOSER_FLAGS}
  - composer require guzzlehttp/guzzle:^7.9 --no-interaction
  - composer require tedivm/stash:^1.2 --no-interaction
script:
  - vendor/bin/phpunit
cache:
  directories:
  - vendor
  - $HOME/.composer/cache
  - $HOME/.cache/phan-ast/build
  - $HOME/setup
after_success:
    - bash <(curl -s https://codecov.io/bash)
